name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          cat <<EOF > anon_api/.env
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DEBUG=${{ secrets.DEBUG }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          EOF
        shell: bash

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . --platform linux/amd64 -t ghcr.io/jimmyflatting/anon-api:latest
          docker push ghcr.io/jimmyflatting/anon-api

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker system prune --filter "until=24h" -f
            docker pull ghcr.io/jimmyflatting/anon-api:latest
            docker stop anon-api
            docker rm anon-api
            docker run -d -p 3000:3000 --name anon-api ghcr.io/jimmyflatting/anon-api:latest
